version: '3.8'

services:
  web:
    container_name: php8
    volumes:
      - ./src:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=binotifyspotipai
      - MYSQL_DBNAME=binotifydb
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=binotifyspotipai
      - MYSQL_DATABASE=binotifydb
      - MYSQL_TCP_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    restart: always
